export const environment = {
  production: false,
  envName: 'hml',
  apiUrl: 'https://hml-api.sistema.com/api',
  appName: 'Sistema [HML]',
  appIcon: 'favicon.ico',
  barColor: '#198754',
  barTextColor: '#ffffff',
  pageTitleBgColor: '#fd7e14',
  pageTitleTextColor: '#ffffff',
  btnInserirBg: '#198754',
  btnInserirText: '#ffffff',
  btnVisualizarBg: '#0dcaf0',
  btnVisualizarText: '#000000',
  btnAlterarBg: '#ffc107',
  btnAlterarText: '#000000',
  btnExcluirBg: '#dc3545',
  btnExcluirText: '#ffffff',
  btnSalvarBg: '#0d6efd',
  btnSalvarText: '#ffffff',
  btnCancelarBg: '#6c757d',
  btnCancelarText: '#ffffff',
  btnSimBg: '#198754',
  btnSimText: '#ffffff',
  btnNaoBg: '#dc3545',
  btnNaoText: '#ffffff',
};
